"""add telegram tables and user timezone fields

Revision ID: 67c4576dc134
Revises: 801849a2d639
Create Date: 2026-04-14 20:28:26.630376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67c4576dc134'
down_revision: Union[str, None] = '801849a2d639'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_conversations',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('step', sa.String(length=32), nullable=False),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('chat_id', name=op.f('pk_telegram_conversations'))
    )
    op.create_table('telegram_connection_codes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_telegram_connection_codes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_connection_codes'))
    )
    with op.batch_alter_table('telegram_connection_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telegram_connection_codes_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_telegram_connection_codes_user_id'), ['user_id'], unique=False)

    op.create_table('telegram_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_username', sa.String(length=64), nullable=True),
    sa.Column('linked_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_telegram_links_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_links')),
    sa.UniqueConstraint('user_id', name=op.f('uq_telegram_links_user_id'))
    )
    with op.batch_alter_table('telegram_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telegram_links_chat_id'), ['chat_id'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('summary_time', sa.String(length=5), server_default='10:00', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('summary_time')
        batch_op.drop_column('timezone')

    with op.batch_alter_table('telegram_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telegram_links_chat_id'))

    op.drop_table('telegram_links')
    with op.batch_alter_table('telegram_connection_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telegram_connection_codes_user_id'))
        batch_op.drop_index(batch_op.f('ix_telegram_connection_codes_code'))

    op.drop_table('telegram_connection_codes')
    op.drop_table('telegram_conversations')
    # ### end Alembic commands ###
