"""add cv_id to applications

Revision ID: abd80db79dbd
Revises: 7b3bcf9fa0c1
Create Date: 2026-04-06 17:45:00.469227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abd80db79dbd'
down_revision: Union[str, None] = '7b3bcf9fa0c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cv_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_applications_cv_id'), ['cv_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_applications_cv_id_cvs'), 'cvs', ['cv_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_applications_cv_id_cvs'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_applications_cv_id'))
        batch_op.drop_column('cv_id')

    # ### end Alembic commands ###
